### ISSUE TITLE
docker-compose.yml should imply secret generation for secrets.yml

### ISSUE THREAD

**Issue by lukemalinowski** [mitre/heimdall#36]
Dockerfile and docker-compose.yml have the ability to manage secrets through docker which limits leakage by avoiding storing them un-encrypted on the main FS. They are mounted to /run/secrets/ in the container.

**Comment by rbclark** [comment]
This issue should be solved on the current master branch, the new instructions for how to use the docker container can be found at https://github.com/mitre/heimdall#setup-docker-container
