### ISSUE TITLE
add version tagging to the docker hub releases using the new VERSION file

### ISSUE THREAD

**Issue by aaronlippold** [mitre/heimdall#44]
right now we just have 'lastest' we should also have v2.x.y or v3.0.0 in case someone needs to pin for whatever reason.

**Comment by rbclark** [comment]
I've enabled builds on tags but for some reason dockerhub doesn't seem to be picking them up and building them...

**Comment by rbclark** [comment]
I am afraid it might not pick up the tags until a new commit is pushed to them but I am unsure if that is the case. Everything looks right based on the documentation provided on the page:

<img width="1050" alt="Screen Shot 2019-08-07 at 3 59 17 PM" src="https://user-images.githubusercontent.com/2308869/62653799-56f35d00-b92c-11e9-911f-1f67404a2ecf.png">

**Comment by aaronlippold** [comment]
Fixed, and updated on docker hub
