### ISSUE TITLE
Change "Profile Controls" label to "Tests"

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall#51]
As done in Heimdall-lite (Well, actually making things more generic than heimdall-lite)

**Comment by Mitriol** [comment]
I would argue they should be "Profile Tests" since a Control doesn't necessarily have results. Controls from a Profile file won't actually have results data - it feels a bit silly to call something with no Results a Result.

**Comment by ejaronne** [comment]
Let's simplify further and drop the word "Profile". Change it to simply "Tests". 
Because:
- Sonarqube does various tests, and finds bugs and such
- OWASP ZAP does the same
- as does Fortify
 -- heimdall_tools converts these to heimdall data format jsons readable by Heimdall
--- but none use the term controls *or* profile, for that matter.

Heimdall is for more than InSpec profiles and its controls.
Finally, since the listing area displays more than pass/fail results as you point out, and indeed displays the entire test, I concur and propose simply "Tests"

Thanks!
