### ISSUE TITLE
For count tiles, change "Findings" label to "Test Counts"

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall#54]
For the count tiles, Heimdall-lite doesn't label the section in any way. "Findings" is a loaded term for security assessors. Tools like InSpec provide raw results, humans determine if it is indeed a security finding. If something *must* be there, please simply call it Test Counts". Thanks!

**Comment by lukemalinowski** [comment]
@ejaronne Export CAAT uses the term "Finding" several times for the data it outputs. Should it be changed or does the CAAT format require the term "Finding"?

**Comment by ejaronne** [comment]
CAAT uses the term Findings.  A human decides if it truly is a finding, by making the spreadsheet "official" and uploading into the agencies system of record. On that note however, I just thought of something: The filename generated should be: "DRAFT-CAAT..." not "CAAT..."

**Comment by lukemalinowski** [comment]
Thanks for the information!
