### ISSUE TITLE
Change "Control" to "Test" for Status and Impact labels

### ISSUE THREAD

**Issue by ejaronne** [mitre/heimdall#57]
To avoid confusion with NIST SP 800-53 controls, and results from non-InSpec derived jsons for static or dynamic tool data converted to json using heimdall-tools, recommend changing:
"Control Status" to "Result Status" and
"Control Impact" to "Result Impact"

Thanks!

**Comment by Mitriol** [comment]
See https://github.com/mitre/heimdall/issues/51#issuecomment-518871349

**Comment by ejaronne** [comment]
Per https://github.com/mitre/heimdall/issues/51#issuecomment-518877754, Let's simplify further to:

"Test Status" and "Test Impact"

**Comment by lukemalinowski** [comment]
Resolved by
f21767b
