### ISSUE TITLE
Custom context root for heimdall

### ISSUE THREAD

**Issue by gkollengode** [mitre/heimdall#61]
We have an Amazon ECS cluster running Heimdall server fronted by an Application Load Balancer. We need a  a way to create a custom context root for the heimdall application so the ALB can forward requests ?

**Comment by rbclark** [comment]
I have not messed with amazon ALB at all so I'm not sure if the changes required will be any more in-depth, however you should be able to add `config.relative_url_root = "/heimdall"` to https://github.com/mitre/heimdall/blob/master/config/environments/production.rb and then the server should serve all urls with `/heimdall/` in front of them. If that works let me know and I can add an environment variable configuration for you to pass in which will do this for you.

**Comment by aaronlippold** [comment]
We would want to set this up as an ENV var as well correct, with a fall through of `|| ''` I would assume?

**Comment by gkollengode** [comment]
If I add config.relative_url_root = "/heimdall" , the context switch works, but the css rendering is off no images load

**Comment by robthew** [comment]
You could try precompiling the assets, running 'bundle exec rake assets:precompile', just to make sure. If that doesn't work, could you open your browser's development window and load a page with the 'Network' tab open? It should show all the paths it is trying to load and failing. That info will help us debug what is going on.

**Comment by rbclark** [comment]
One piece that is a bit unclear to me is what method is being used to deploy heimdall here, is it being deployed with docker or with the deb/rpm package? That might affect the additional steps required to get this working.

**Comment by lukemalinowski** [comment]
In deprecated Heimdall mongo we did something like the following:

``` ruby
map Rails.application.config.relative_url_root || "/" do
  run Rails.Application
end
```

And add a check in config to set `config.relative_url_root = ENV["RAILS_RELATIVE_URL_ROOT"]`

This fixes all the routing to respect relative_url_root.

The current version of the rails docs do not state that this needs to be done, so it shouldnt have to be. I'll test it and post results, but it would be nice if we got  some network debugger screenshots from @gkollengode

**Comment by lukemalinowski** [comment]
Just confirming that the change I suggested does work, but based off rbclark and robthew's comments should not be necessary, and I am likely not testing the app correctly

@gkollengode would your version happen to look like this:
<img width="1680" alt="Screen Shot 2019-08-15 at 1 45 10 PM" src="https://user-images.githubusercontent.com/40170735/63114517-0e0e5a80-bf63-11e9-9eab-d68d9fb83245.png">

I cannot reproduce your exact issue as I do not have heimdall running under ALB

**Comment by gkollengode** [comment]
It is being deployed with docker
