### ISSUE TITLE
Update Postgresql Confuguration section

### ISSUE THREAD

**Issue by gkollengode** [mitre/heimdall#62]
We are trying to use a remote PostgreSQL server for the Heimdall server and the config section  is missing variables to set up all the items
Have a work around by modifying the database.yml like so
``
  <<: *default
  database: heimdall
  host: <%= ENV['POSTGRES_TCP_ADDR'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['POSTGRES_PORT'] %>
 ``

**Comment by hunleyd** [comment]
you should probably match the expected PG variable names as documented on https://www.postgresql.org/docs/11/libpq-envars.html

**Comment by rbclark** [comment]
Rails does have support for leaving basically all of the Database config exposed to the user, see:

https://github.com/mitre/heimdall/blob/master/config/database.yml#L71-L80

```
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
```

If we were to update the default database.yml to have that block it would provide the flexibility you're requesting. I think this is a reasonable change.

**Comment by aaronlippold** [comment]
Agreed, do we also want to have a default as well or require that the ENV var be set on all deployments?

**Comment by aaronlippold** [comment]
@hunleyd @rbclark @robthew how much abstraction do we think we want to put into place? aka just DATABASE_URL or multiple ENV vars like DATABASE_IP, DB_ADMIN, DB_PASSWORD, and DATABASE_URL can be either the passed in string or a combination of the other ENV vars? etc etc.

**Comment by aaronlippold** [comment]
Also, it seems to me like we should also provide PG_DB_NAME as well if we are going this route.

**Comment by aaronlippold** [comment]
I also agree with @hunleyd - if there is a defined standard naming convention for PG DB vars - we should respect it and *link to the docs* in the readme :)

**Comment by hunleyd** [comment]
> @hunleyd @rbclark @robthew how much abstraction do we think we want to put into place? aka just DATABASE_URL or multiple ENV vars like DATABASE_IP, DB_ADMIN, DB_PASSWORD, and DATABASE_URL can be either the passed in string or a combination of the other ENV vars? etc etc.

I've always been a fan of using the URI instead of vars myself:
postgresql://user:pass@host:port/dbname?sslmode=whatever

see 34.1.1.2 oin https://www.postgresql.org/docs/current/libpq-connect.html

**Comment by aaronlippold** [comment]
Ok. That seems to be the most direct solution. So if we have concensious
then let's go adhead with the URI env var approach.
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by rbclark** [comment]
I was also thinking just URL approach, maintaining 2 methods is just messy. So messy that rails just provides the 2nd method as a comment in the database.yml so you an choose between them, instead of supporting both.
