### ISSUE TITLE
Use Dockerhub to distribute pre-built images

### ISSUE THREAD

**Issue by rbclark** [mitre/heimdall#88]
Requiring end users to always build their own image is less than ideal. Most of the time it is possible and more convenient to provide a prebuilt image through dockerhub. Additionally, it is a lot easier for users who are behind a proxy.

**Comment by Bialogs** [comment]
We have had good experience with packager

**Comment by rbclark** [comment]
We have had decent experience with packager, however I'd say one of my biggest takeaways from using packager is it is probably easier for most cases to just build on Dockerhub and distribute it if you do not have any other constraints. One of the companies that has done it best IMO is Gitlab. They have been distributing a prebuilt Docker image that is so stable that we have been able to put it on an automatic update cronjob nightly for nearly 2 years and it has never broken our Gitlab server and works every time behind a proxy since it is prebuilt. Having one command that can be run to reliably pull in every update you make is extremely beneficial to end users.

**Comment by rbclark** [comment]
This has since been solved by the new packager and docker setup.
