### ISSUE TITLE
Control impact level 'low' displays as 'Not Applicable' and then causes system error

### ISSUE THREAD

**Issue by adamday2** [mitre/heimdall#98]
When setting `impact: 'low'` on a control, it causes the control to be marked as "Not Applicable" in heimdall and results in the following error on the evaluation page. There were no relevant errors in the docker logs that I could see, but it appears the webserver logs may not be routing to stdout in the container.

This error is fixed by setting `impact: 0.2`, so it may to be have something to do with the translation of low to 0.01 in the output. 

Evaluations Page Error:
> We're sorry, but something went wrong. If you are the application owner check the logs for more information.

Environment: docker

JSON which causes error:
https://gist.github.com/adamday2/bfbf561814ba5d1e70aea8f9ea1348bc

**Comment by adamday2** [comment]
After a little digging, there seems to be a misalignment between the categories as described here:
https://www.inspec.io/docs/reference/dsl_inspec/

> 0.0 to <**0.01** these are controls with no impact, they only provide information
0.01 to <0.4 these are controls with low impact
0.4 to <0.7 these are controls with medium impact
0.7 to <0.9 these are controls with high impact
0.9 to 1.0 these are critical controls

And what is in the code:
https://github.com/mitre/heimdall/blob/85354c26551dedb43ce607a6c5c06560c3e13c74/app/models/control.rb#L142

Looking at https://nvd.nist.gov/vuln-metrics/cvss, it looks like your implementation is correct, but doesn't match the output from InSpec

**Comment by aaronlippold** [comment]
Hello, we had a call with the InSpec folks yesterday. Your ticket has been put into the work stream. However, an even faster approach is to submit a PR for the quick fix and then they can review it and merge it in.

**Comment by aaronlippold** [comment]
Fixed in https://github.com/inspec/inspec/pull/3961

**Comment by aaronlippold** [comment]
closing
